# Generated by Django 5.0.3 on 2024-07-11 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('PID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('url', models.URLField()),
                ('rating', models.FloatField()),
                ('image', models.URLField(blank=True, max_length=255, null=True)),
                ('specifications', models.TextField()),
                ('predicted_rating', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('PID', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('specifications', models.TextField()),
                ('predicted_rating', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('review', models.TextField()),
                ('up', models.IntegerField(default=0)),
                ('down', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.product')),
            ],
        ),
    ]
