# Generated by Django 5.0.3 on 2024-07-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_remove_wishlist_rating_wishlist_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='PID',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
